project:
  type: website

publish:
  provider: gh-pages
  repo: https://github.com/mszeihen/DatabaseProject-5725.git

website:
  title: "COP-5725---Group-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: tableSQL.qmd
        text: Table SQL
      - href: queriesSQL.qmd
        text: Queries SQL
      - href: erEnglish.qmd
        text: English Structured Relationships
      - href: ERDiagram_Assignment.qmd
        text: ERD Assignment

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



