---
title: "About"
---

This is a group project. A group may have 3 or 4 people. For this project, I would like only one 
submission per group. Make sure you include all participating group members, otherwise they 
will not get credit. Group members you can find it through Ed discussion forum. For example, 
you can go through the Introduce yourself page or create a thread to find group members.  
The project is meant to bring all the concepts that you learned in this class together. So, you start 
off by designing the database, then you proceed to mapping and implementing it – so you go all 
the way from designing a database, documenting it, to implementing it in MySQL.  

# The project  
Design and develop a database of your choice that includes at least:  
1. 5-7 regular strong entities.  
2. One strong and weak entities relationship 
3. One supertype and subtype relationship   
4. One 1:1, one 1:M, and one M: N relationship.  
5. Other notes:  
  o Do not emphasize on too many attributes for the entities.  
  o Three to four attributes for each entity will be enough.  
  o Make sure to include a primary key for each entity and use foreign key wherever 
  needed.

# Phases of the projects:

1. Phase 1 
  a. Identify entities, relationships, attributes 
  b. Design EER diagram 

2. Phase 2 
  a. Include cardinality for relationships and attributes in EER diagram  
  b. Demonstrate at least one example of strong and weak entities 
  c. Demonstrate at least one example of supertype and subtype entities 

3. Phase 3 
  a. Write the specifications for your database (Structured English). You need to write 
  out the specifications for only one entity.  
  b. Write out ALL the cardinalities and participation ratios (for all relationships), and 
  explain all the strong and weak, supertype and subtype relationships. 
  c. Write all the column and table constraints.  
  d. Normalization: Try to achieve at least 3NF design.

4. Phase 4 
  a. Implement the EER diagram into MySQL database 
  b. Create tables according to the mapping. For this part, submit a description of the 
  tables created in the report.  
  c. Add at least five records. Submit a copy of all the records inserted in the report.  
  d. Write and answer some (at least five) “reasonable” queries for your database.

  When I say reasonable queries – I mean 3-4 table joins to use most of the tables or 
  group of tables in your database. You should not have tables that are of no use. 
  For this part, first, write the queries in English – that is, telling me what you are 
  finding in the queries. Then, present the query and finally present the output of the 
  query. 
  e. Include the imported diagram using reverse engineering.

# Submission guidelines of the projects:  
  1. Include all the group member’s name at the top in the project.  
  2. Organize the report in four phases.  
  3. Submit one PDF file including all the phases. 

Good Luck!!
